---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app.kubernetes.io/instance: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
