---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: semantic-sensei

labels:
  - pairs:
      app.kubernetes.io/app: semantic-sensei
    includeSelectors: true

resources:
  - ../base/backend
  - ../base/frontend
  - ../base/postgres
  - ingress.yaml
  - namespace.yaml
