---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

secretGenerator:
  - name: backend-config
    files:
      - config.yaml

resources:
  - ../../base/backend

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
      name: backend
      namespace: default
