---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

secretGenerator:
  - name: postgres-env
    envs:
      - env.env

resources:
  - ../../base/postgres

patches:
  - path: statefulset.patch.yaml
    target:
      kind: StatefulSet
      name: postgres
      namespace: default
