openapi: "3.0.2"
info:
  title: Semantic Sensei
  version: "1.0"
servers:
  - url: http://localhost:8080/api/

paths:
  /project:
    post:
      description: "Creates a new project"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProject"
      responses:
        201:
          description: "The created project"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /project/{id}:
    get:
      description: "Gets the project with the given ID"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            x-go-type: int64
      responses:
        200:
          description: "The project with the given ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        404:
          description: "The project with the given ID does not exist"

  /project/{project_id}/classification_task_label:
    post:
      description: "Creates a new classification task label"
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
            x-go-type: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateClassificationTaskLabel"
      responses:
        201:
          description: "The created classification task label"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassificationTaskLabel"

  /project/{project_id}/classification_task_label/{id}:
    get:
      description: "Gets the classification task label with the given ID"
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
            x-go-type: int64
        - name: id
          in: path
          required: true
          schema:
            type: integer
            x-go-type: int64
      responses:
        200:
          description: "The classification task label with the given ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassificationTaskLabel"
        404:
          description: "The classification task label with the given ID does not exist"

  /project/{project_id}/classification_task:
    post:
      description: "Creates a new classification task"
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
            x-go-type: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateClassificationTask"
      responses:
        201:
          description: "The created classification task"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassificationTask"

  /project/{project_id}/classification_task/{id}:
    get:
      description: "Gets the classification task with the given ID"
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
            x-go-type: int64
        - name: id
          in: path
          required: true
          schema:
            type: integer
            x-go-type: int64
      responses:
        200:
          description: "The classification task with the given ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassificationTask"
        404:
          description: "The classification task with the given ID does not exist"

components:
  schemas:
    CreateProject:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
        - description

    Project:
      type: object
      properties:
        id:
          type: integer
          x-go-type: int64
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - description
        - created_at

    CreateClassificationTaskLabel:
      type: object
      properties:
        label:
          type: string
      required:
        - label

    ClassificationTaskLabel:
      type: object
      properties:
        id:
          type: integer
          x-go-type: int64
        project_id:
          type: integer
          x-go-type: int64
        label:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - project_id
        - label
        - created_at

    CreateClassificationTask:
      type: object
      properties:
        llm_input:
          type: string
        llm_output:
          type: string
        embedding:
          type: string
          format: byte
      required:
        - llm_input
        - llm_output
        - embedding

    ClassificationTask:
      type: object
      properties:
        id:
          type: integer
          x-go-type: int64
        project_id:
          type: integer
          x-go-type: int64
        llm_input:
          type: string
        llm_output:
          type: string
        embedding:
          type: string
          format: byte
        created_at:
          type: string
          format: date-time
        label_id:
          type: integer
          x-go-type: int64
      required:
        - id
        - project_id
        - llm_input
        - llm_output
        - embedding
        - created_at
