---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
              name: psql
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432 -d "$POSTGRES_DB"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432 -d "$POSTGRES_DB"
